/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BowlingGameKata;

import org.junit.Test;
import static org.junit.Assert.*;

public class BowlingGameTest {
    @Test
    public void BowlingGameAllMissesEqualsZero() {
        BowlingGame game = new BowlingGame();

        for(int i = 0; i < 20; i++) {
            game.roll(0);
        }
        assertEquals(0, game.getScore());
    }

    @Test
    public void BowlingGameAllOnesEqualsTwenty() {
        BowlingGame game = new BowlingGame();

        for(int i = 0; i < 20; i++) {
            game.roll(1);
        }
        assertEquals(20, game.getScore());
    }

    @Test
    public void BowlingGameOneSpareAndThenRollFiveEqualsTwenty() {
        BowlingGame game = new BowlingGame();

        game.roll(5);
        game.roll(5);
        game.roll(5);
        for(int i = 0; i < 17; i++) {
            game.roll(0);
        }
        assertEquals(20, game.getScore());
    }

    @Test
    public void BowlingGameOneStrikeAndThenRollTwoAndThreeEqualsTwenty() {
        BowlingGame game = new BowlingGame();

        game.roll(10);
        game.roll(2);
        game.roll(3);
        for(int i = 0; i < 17; i++) {
            game.roll(0);
        }
        assertEquals(20, game.getScore());
    }

    @Test
    public void BowlingGameAllStrikesEqualsThreeHundred() {
        BowlingGame game = new BowlingGame();

        for(int i = 0; i < 12; i++) {
            game.roll(10);
        }
        assertEquals(300, game.getScore());
    }
}
