/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BowlingGameKata;

public class BowlingGame {

    public void roll(int i) {
    }

    public int getScore() {
        return 0;
    }
}
