/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BowlingGameKata;

public class BowlingGame {

    private int score = 0;
    private int rollIndex = 0;
    private int[] rolls = new int[21];


    public void roll(int i) {
        rolls[rollIndex] = i;
        rollIndex++;
    }

    public int getScore() {
        for(int i = 0; i < rollIndex; i++) {
            if(rolls[i] == 10) {
                if(i >= rollIndex - 2) {
                    break;
                }
                score += 10 + rolls[i + 1] + rolls[i + 2];
            } else if(rolls[i] + rolls[i + 1] == 10) {
                score += 10 + rolls[i + 2];
                i++;
            } else {
                score += rolls[i];
            }
        }

        return score;
    }
}
