/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BowlingGameKata;

public class BowlingGame {

    private int score = 0;

    public void roll(int i) {
        score += i;
    }

    public int getScore() {
        return score;
    }
}
